### ISSUE TITLE
.bouncycastle errors - could you share the jar file you used ?

### ISSUE THREAD

**Issue by smarty1234** [verhas/License3j#14]
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DEREncodable
        at org.bouncycastle.openpgp.PGPKeyRing.readSignaturesAndTrust(Unknown Source)
        at org.bouncycastle.openpgp.PGPKeyRing.readUserIDs(Unknown Source)
        at org.bouncycastle.openpgp.PGPSecretKeyRing.<init>(Unknown Source)
        at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
        at org.bouncycastle.openpgp.PGPSecretKeyRingCollection.<init>(Unknown Source)
        at com.verhas.licensor.License.loadKey(License.java:440)
        at com.verhas.licensor.License.loadKey(License.java:404)
        at com.verhas.licensor.License.loadKey(License.java:250)
        at License3j.encode(License3j.java:34)
        at License3j.main(License3j.java:152)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.DEREncodable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

--------
Exception in thread "main" java.lang.SecurityException: class "org.bouncycastle.asn1.DEREncodable"'s signer information does not match signer information of other classes in theame package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.bouncycastle.openpgp.PGPKeyRing.readSignaturesAndTrust(Unknown Source)
        at org.bouncycastle.openpgp.PGPKeyRing.readUserIDs(Unknown Source)
        at org.bouncycastle.openpgp.PGPSecretKeyRing.<init>(Unknown Source)
        at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
        at org.bouncycastle.openpgp.PGPSecretKeyRingCollection.<init>(Unknown Source)
        at com.verhas.licensor.License.loadKey(License.java:440)
        at com.verhas.licensor.License.loadKey(License.java:404)
        at com.verhas.licensor.License.loadKey(License.java:250)
        at License3j.encode(License3j.java:34)
        at License3j.main(License3j.java:152)
:lib/bcpg-jdk15+-1.46.jar:lib/bcpg-jdk15on-1.46.jar:lib/bcpg-jdk16-1.46.jar:lib/bcprov-jdk15on-1.50.jar:lib/bcprov-jdk15on-152.jar:lib/bcprov-jdk16-140.jar:lib/bcprov-jdk16-1.44ar:lib/bcprov-jdk16-1.44-sources.jar:lib/license3j-1.0.5.jar:lib/license3j-1.0.8-SNAPSHOT.jar:lib/license3j-1.0.8-SNAPSHOT-javadoc.jar:lib/License3j.class

**Comment by verhas** [comment]
Jar files are all shared in the maven repositories. Developers using License3j are expected to undertand the basic structure of a maven project, how to use repository and the basic information needed to open a problem ticket. A stack trace dump of an outdated (non-specified version) of the software and asking for a jar file publicly available can not be considered as matching.

**Comment by smarty1234** [comment]
otal 10660
-rw-r--r-- 1 mkumar pspblmentors   77815 May 20 12:33 license3j-1.0.8-SNAPSHOT-javadoc.jar
-rw-r--r-- 1 mkumar pspblmentors   24086 May 20 12:34 license3j-1.0.8-SNAPSHOT.jar
-rw-r--r-- 1 mkumar pspblmentors    5425 May 20 12:35 License3j.class
-rw-r--r-- 1 mkumar pspblmentors 2902942 May 20 13:01 bcprov-jdk15on-152.jar
-rw-r--r-- 1 mkumar pspblmentors   22116 May 20 13:08 license3j-1.0.5.jar
-rw-r--r-- 1 mkumar pspblmentors  174074 May 20 13:23 bcpg-jdk16-1.46.jar
-rw-r--r-- 1 mkumar pspblmentors  165630 May 20 13:30 bcpg-jdk15+-1.46.jar
-rw-r--r-- 1 mkumar pspblmentors  165630 May 20 13:30 bcpg-jdk15on-1.46.jar
-rw-r--r-- 1 mkumar pspblmentors 2732684 May 20 13:36 bcprov-jdk15on-1.50.jar
-rw-r--r-- 1 mkumar pspblmentors 1699426 May 20 13:38 bcprov-jdk16-1.44.jar
-rw-r--r-- 1 mkumar pspblmentors 1273149 May 20 13:43 bcprov-jdk16-1.44-sources.jar
-rw-r--r-- 1 mkumar pspblmentors 1652404 May 20 13:52 bcprov-jdk16-140.jar
I tried all possible jars

**Comment by smarty1234** [comment]
it looks issue with your license.sh file in linux - the following command is not exact equivalent of the .bat file command. I have all the jars in "lib" and it complains. could you please update - how to use the .sh - I have provided all the fields that are mentioned in 

 E:\PROJECTS\research\licensor>license3j.bat encode --license-file=license-plain.
  txt --keyring-file="c:\Documents and Settings\verhas\Application Data\gnupg\secr
  ing.gpg" --key=GrooWikiDemoKey --password=******** --output=license.out

just replaced license3j.bat  with license3j.sh




./license3j.sh encode --license-file=license-plain.txt --keyring-fil.................

Usage: java -cp license3j.jar License3j encode options
 mandatory options are: 
--license-file, --keyring-file, --key, --password, --output
Exception in thread "main" java.lang.SecurityException: class "org.bouncycastle.asn1.DEREncodable"'s signer information does not match signer information of other classes in the same package
