### ISSUE TITLE
Exception  when use a string with colon

### ISSUE THREAD

**Issue by mueller-jens** [verhas/License3j#66]
I have a use case where i have to a string with colon in the license file. If i try this i get an Exception.

Here a sample code:

```
        File f = new File("test.lic");
        License license = new License();
        license.add(Feature.Create.stringFeature("id", "03:12:13"));
        license.add(Feature.Create.dateFeature("feature1", new Date()));
        license.add(Feature.Create.dateFeature("feature2", new Date()));
        LicenseWriter licenseWriter = new LicenseWriter(f.getAbsoluteFile());
        licenseWriter.write(license, IOFormat.STRING);
        
        LicenseReader reader = new LicenseReader(f);
        License license1  = reader.read(IOFormat.STRING);
        System.out.println(license1.get("id").getString());
```

output

```
Exception in thread "main" java.lang.IllegalArgumentException: Feature string representation needs '=' after the type
	at javax0.license3j.Feature.splitString(Feature.java:87)
	at javax0.license3j.License$Create.from(License.java:494)
	at javax0.license3j.io.LicenseReader.read(LicenseReader.java:109)
	at com.x.main(x.java:32)

```
Can you please check if it is a bug?

**Comment by verhas** [comment]
Yes, it is a bug. I will create a new release ASAP

**Comment by mueller-jens** [comment]
Thanks

**Comment by mueller-jens** [comment]
Thanks for the fast fix. It works fine for me.
